In [17]:
from pandas import read_csv, DataFrame

In [33]:
df = read_csv('catalog1/cat1.csv')

In [34]:
df['class'].value_counts()

1    595
0     54
Name: class, dtype: int64

In [4]:
df_0 = df[df['class'] == 0]

In [5]:
df_0['class'].value_counts()

0    54
Name: class, dtype: int64

In [24]:
def resample(df, n_samples, replace=True, random_state=None):
    temp = DataFrame()
    length_df = len(df)
    base_size = 10
    if replace == False:
        assert n_samples <= length_df
        return df.sample(n=n_samples, random_state=random_state)
    else:
        assert 2 * length_df >= n_samples
        while n_samples > base_size:
            temp = temp.append(df.sample(n=base_size), ignore_index=True)
            n_samples -= 10
        temp = temp.append(df.sample(n=n_samples))
    return temp

In [25]:
new_df_0 = resample(df=df_0, n_samples=90)

In [26]:
# df_0 = df[df['class'] == 0]
df_0.head()

,Unnamed: 0,galex_objid,sdss_objid,u,g,r,i,z,extinction_u,extinction_g,...,r-i,r-z,i-z,fuv-nuv,fuv-u,fuv-g,fuv-r,fuv-i,fuv-z,pred
0,0,2.489297e+18,1.237665e+18,18.286291,16.968243,16.334318,16.039885,15.857203,0.094921,0.073962,...,0.294434,0.477116,0.182682,-2.119261,-4.368679,-5.686728,-6.320652,-6.615086,-6.797768,0
10,10,2.491021e+18,1.237667e+18,21.448120,20.221476,19.786520,19.566395,19.629253,0.041427,0.032280,...,0.220125,0.157267,-0.062859,-0.761206,-2.605324,-3.831968,-4.266924,-4.487049,-4.424191,1
23,23,3.056821e+18,1.237668e+18,22.134577,21.255135,21.224594,21.070549,21.080980,0.080741,0.062913,...,0.154045,0.143614,-0.010431,0.021778,-1.137417,-2.016859,-2.047400,-2.201445,-2.191013,1
51,51,6.374681e+18,1.237662e+18,20.302319,20.018528,20.344492,20.576990,20.919077,0.061727,0.048097,...,-0.232498,-0.574585,-0.342087,0.239292,0.438374,0.154583,0.480547,0.713045,1.055132,0
76,76,6.374681e+18,1.237664e+18,20.439363,20.002916,19.726328,19.044205,18.522968,0.068487,0.053364,...,0.682123,1.203360,0.521236,-0.127451,-0.040613,-0.477060,-0.753649,-1.435772,-1.957008,1

In [27]:
new_df_0.head(20)

,Unnamed: 0,galex_objid,sdss_objid,u,g,r,i,z,extinction_u,extinction_g,...,r-i,r-z,i-z,fuv-nuv,fuv-u,fuv-g,fuv-r,fuv-i,fuv-z,pred
0,391,3.057137e+18,1.237665e+18,21.481510,20.728798,20.817604,20.937922,20.824234,0.071836,0.055974,...,-0.120317,-0.006630,0.113688,-1.112761,-2.538553,-3.291265,-3.202459,-3.082142,-3.195829,1
1,597,6.378762e+18,1.237663e+18,15.849100,15.634081,16.076437,16.299097,16.521378,0.099889,0.077833,...,-0.222660,-0.444941,-0.222281,-0.114840,-0.275520,-0.490540,-0.048183,0.174477,0.396757,0
2,397,6.379325e+18,1.237665e+18,20.285851,20.252367,20.611416,20.860336,21.091360,0.059841,0.046628,...,-0.248920,-0.479944,-0.231024,0.271544,0.612679,0.579195,0.938244,1.187164,1.418188,0
3,390,6.378727e+18,1.237668e+18,20.531384,20.145739,20.355513,20.620770,20.867689,0.078877,0.061461,...,-0.265257,-0.512177,-0.246920,-0.240528,-0.306337,-0.691982,-0.482208,-0.216951,0.029968,0
4,569,6.374856e+18,1.237667e+18,16.825037,15.607949,15.574786,15.595540,15.661098,0.080191,0.062484,...,-0.020754,-0.086311,-0.065557,-2.589365,-3.816328,-5.033416,-5.066579,-5.045825,-4.980268,0
5,229,6.378621e+18,1.237668e+18,17.175303,15.975873,15.949412,15.990144,16.026575,0.177486,0.138296,...,-0.040731,-0.077163,-0.036431,-2.745800,-4.436422,-5.635852,-5.662313,-5.621581,-5.585150,0
6,557,6.374892e+18,1.237665e+18,19.959137,19.572088,19.517006,18.610332,17.822611,0.070063,0.054593,...,0.906673,1.694395,0.787722,0.192751,0.336288,-0.050760,-0.105843,-1.012516,-1.800238,0
7,577,6.374856e+18,1.237665e+18,19.765282,19.660999,20.007305,20.290073,20.394323,0.044487,0.034664,...,-0.282768,-0.387018,-0.104250,0.229120,0.480322,0.376040,0.722345,1.005114,1.109364,0
8,417,3.156041e+18,1.237668e+18,22.454351,21.402727,21.312325,21.436291,21.581902,0.126532,0.098593,...,-0.123966,-0.269577,-0.145611,0.503090,-0.743258,-1.794882,-1.885284,-1.761318,-1.615707,1
9,272,6.378727e+18,1.237668e+18,19.993994,20.060999,20.420309,20.768444,20.732269,0.119884,0.093413,...,-0.348135,-0.311960,0.036175,0.427572,0.707420,0.774426,1.133736,1.481871,1.445696,0
10,563,6.378727e+18,1.237668e+18,19.297325,17.847700,17.417463,17.245628,17.250906,0.081169,0.063246,...,0.171835,0.166557,-0.005278,-1.462059,-3.073046,-4.522671,-4.952908,-5.124743,-5.119465,0
11,418,6.378727e+18,1.237668e+18,19.468637,19.183750,19.479006,19.681135,20.037243,0.139562,0.108746,...,-0.202129,-0.558237,-0.356108,0.287104,0.421759,0.136871,0.432127,0.634256,0.990364,0
12,642,6.378727e+18,1.237668e+18,20.334911,20.097109,20.468292,20.792000,21.226725,0.125980,0.098163,...,-0.323708,-0.758432,-0.434725,0.144064,0.249123,0.011320,0.382504,0.706211,1.140936,0
13,338,6.379290e+18,1.237665e+18,21.254183,20.496405,19.967834,19.126457,18.582846,0.063931,0.049815,...,0.841377,1.384989,0.543612,0.093294,-0.517752,-1.275530,-1.804100,-2.645477,-3.189089,1
14,239,6.378621e+18,1.237668e+18,20.074879,19.977060,20.296528,20.594790,21.165041,0.170629,0.132953,...,-0.298262,-0.868513,-0.570251,0.385138,0.543922,0.446104,0.765572,1.063833,1.634085,0
15,575,6.378762e+18,1.237663e+18,20.020714,19.573851,19.946411,20.179052,20.163719,0.126764,0.098774,...,-0.232641,-0.217308,0.015333,-0.515083,-0.824242,-1.271105,-0.898544,-0.665903,-0.681236,0
16,629,6.374892e+18,1.237665e+18,20.109095,19.691797,19.591894,19.643299,19.559032,0.060723,0.047315,...,-0.051405,0.032862,0.084267,-0.672718,-1.711824,-2.129122,-2.229025,-2.177620,-2.261887,1
17,417,3.156041e+18,1.237668e+18,22.454351,21.402727,21.312325,21.436291,21.581902,0.126532,0.098593,...,-0.123966,-0.269577,-0.145611,0.503090,-0.743258,-1.794882,-1.885284,-1.761318,-1.615707,1
18,634,6.374856e+18,1.237667e+18,18.729479,18.745176,19.144787,19.441147,19.767282,0.083866,0.065348,...,-0.296360,-0.622496,-0.326136,0.336838,0.785507,0.801205,1.200815,1.497175,1.823311,0
19,174,6.374892e+18,1.237665e+18,17.507212,16.211807,16.366768,16.497257,16.575453,0.065022,0.050665,...,-0.130489,-0.208685,-0.078196,-1.316824,-2.580589,-3.875994,-3.721033,-3.590544,-3.512348,1

In [29]:
df_1 = df[df['class'] == 1]
new_df_1 = resample(df_1, n_samples=200, replace=False, random_state=42)

In [30]:
new_df = df_0.append(df_1)

In [31]:
from sklearn.utils import shuffle
new_df = shuffle(new_df)

In [32]:
new_df.head()

,Unnamed: 0,galex_objid,sdss_objid,u,g,r,i,z,extinction_u,extinction_g,...,r-i,r-z,i-z,fuv-nuv,fuv-u,fuv-g,fuv-r,fuv-i,fuv-z,pred
534,534,6.378727e+18,1.237668e+18,19.792803,19.407112,19.383713,19.400934,19.198515,0.102569,0.079921,...,-0.017221,0.185198,0.202419,-1.223055,-1.375669,-1.761360,-1.784760,-1.767538,-1.969957,1
491,491,6.374681e+18,1.237664e+18,21.612337,21.553879,21.439257,21.278425,21.131664,0.056772,0.044236,...,0.160831,0.307592,0.146761,0.605005,-0.436098,-0.494556,-0.609179,-0.770010,-0.916771,1
472,472,6.374821e+18,1.237667e+18,21.113956,20.579866,20.082952,19.821938,19.676403,0.091644,0.071409,...,0.261015,0.406549,0.145535,-0.197081,-1.193077,-1.727167,-2.224081,-2.485096,-2.630630,1
79,79,6.374681e+18,1.237664e+18,20.271046,20.575792,20.212301,20.237785,20.386129,0.076445,0.059565,...,-0.025484,-0.173828,-0.148344,-1.918236,-1.812702,-1.507956,-1.871447,-1.845963,-1.697618,1
628,628,6.374681e+18,1.237665e+18,20.418505,20.429962,20.060781,19.960072,20.299290,0.055518,0.043259,...,0.100710,-0.238508,-0.339218,-0.880262,-2.269684,-2.258226,-2.627407,-2.728117,-2.388899,1

In [44]:
from numpy import array

X_train = array([[2, 3], [3, 1]])
y_train = array([[4, 1]]).reshape(2, 1)

In [41]:
X_train, y_train

(array([[2, 3],
        [3, 1]]), array([[4, 1]]))

In [46]:
from numpy import append

append(X_train, y_train, axis=1)

array([[2, 3, 4],
       [3, 1, 1]])